[build]
  command = ""  # No build step since you only have HTML and JS
  publish = "." # Serve files from the root directory

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
